addSbtPlugin("com.47deg"          % "sbt-microsites"           % "1.0.2")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.3.0")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.31")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.9.0")
