addSbtPlugin("com.47deg"          % "sbt-microsites"           % "1.1.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.3.1")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.32")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.9.0")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"          % "0.6.1")
