name: Release
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - uses: olafurpg/setup-gpg@v3
      - name: Publish
        run: sbt +test ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish_site:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Jekyll
      run: gem install jekyll -v 4
    - name: Publish the microsite
      env:
        GITHUB_TOKEN: ${{ secrets.MICROSITE_GITHUB_TOKEN }}
      run: sbt -J-Xms4G -J-Xmx4G docs/publishMicrosite
